services:

  database:
    image: postgres:18.3-alpine
    ports:
      - 5432:5432
    networks:
      - intranet
    volumes:
      - database-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  system:
    image: node:22-alpine
    init: true
    working_dir: /home/dev
    container_name: badges
    command: sh -c "npm i && npm run dev"
    ports:
      - 3000:3000
    networks:
      - intranet
    volumes:
      - .:/home/dev
    restart: unless-stopped

volumes:
  database-data:

networks:
  intranet:
    driver: bridge